AllCops:
  TargetRubyVersion: 2.1

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 60

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/PerceivedComplexity:
  Max: 15

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Security/Eval:
  Enabled: false

Style/Alias:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'lib/awspec/helper.rb'

Style/StderrPuts:
  Exclude:
    - 'lib/awspec/generator/template.rb'
    - 'lib/awspec/setup.rb'

Style/IfUnlessModifier:
  Enabled: false
