name: Doc

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  doc:
    name: Document
    runs-on: ubuntu-latest
    env:
      DISABLE_AWS_CLIENT_CHECK: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Generate document
      run: bundle exec bin/toolbox docgen > doc/resource_types.md

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        add: 'doc/resource_types.md'
